//Generated by: http://json2ts.com/
export default interface Person {
    name: string;
    height: string;
    mass: string;
    hair_color: string;
    skin_color: string;
    eye_color: string;
    birth_year: string;
    gender: string;
    homeworld: string;
    films: string[];
    species: string[];
    vehicles: string[];
    starships: any[];
    created: Date;
    edited: Date;
    url: string;
}


